version: '3'
services:
 radarr:
  container_name: radarr
  restart: unless-stopped
  ports:
   - 7878:7878
  volumes:
    - /home/adorsi/radarr/config:/config
    - /mnt/media/Movies:/mnt/media/Movies
    - /mnt/media/torrents:/mnt/media/torrents
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=America/Los_Angeles
  image: linuxserver/radarr
 
 sonarr:
  container_name: sonarr
  restart: unless-stopped
  ports:
   - 8989:8989
  volumes:
    - /home/adorsi/sonarr/config:/config
    - /mnt/media/Shows:/mnt/media/Shows
    - /mnt/media/torrents:/mnt/media/torrents
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=America/Los_Angeles
  image: linuxserver/sonarr
  
 prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /home/adorsi/prowlarr/:/config
    ports:
      - 9696:9696
    restart: unless-stopped