### Unpackerr docker-compose.yml Example
### See this URL for variable descriptions and options:
### https://github.com/davidnewhall/unpackerr#docker-env-variables
##################################################################
version: "3.7"
services:

  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    volumes:
      # You need at least this one volume mapped so Unapckerr can find your files to extract.
      # Make sure this matches your Starr apps; the folder mount (/downloads or /data) should be identical.
      - /mnt/media/torrents/completed:/downloads
    restart: always
    # Get the user:group correct so unpackerr can read and write to your files.
    #user: 1000:1000
    #user: 1000:1000
    # What you see below are defaults. You only need to include things you change.
    environment:
      - TZ=Americas/Los_Angeles
      # General config
      - UN_DEBUG=false
      - UN_LOG_FILE=
      - UN_LOG_FILES=10
      - UN_LOG_FILE_MB=10
      - UN_INTERVAL=2m
      - UN_START_DELAY=1m
      - UN_RETRY_DELAY=5m
      - UN_MAX_RETRIES=3
      - UN_PARALLEL=1
      - UN_FILE_MODE=0644
      - UN_DIR_MODE=0755
      # Sonarr Config
      - UN_SONARR_0_URL=http://10.0.10.17:8989
      - UN_SONARR_0_API_KEY=28f49b5bb2e34e28903d469096518407
      - UN_SONARR_0_PATHS_0=/downloads
      - UN_SONARR_0_PROTOCOLS=torrent
      - UN_SONARR_0_TIMEOUT=10s
      - UN_SONARR_0_DELETE_ORIG=true
      - UN_SONARR_0_DELETE_DELAY=5m
      # Radarr Config
      - UN_RADARR_0_URL=http://10.0.10.17:7878
      - UN_RADARR_0_API_KEY=1778f260e709493d9622d9b823daace2
      - UN_RADARR_0_PATHS_0=/downloads
      - UN_RADARR_0_PROTOCOLS=torrent
      - UN_RADARR_0_TIMEOUT=10s
      - UN_RADARR_0_DELETE_ORIG=true
      - UN_RADARR_0_DELETE_DELAY=5m

    security_opt:
      - no-new-privileges:true