services:
  radarr:
    container_name: radarr
    restart: unless-stopped
    network_mode: service:transmission-openvpn
    depends_on:
      - transmission-openvpn
    volumes:
      - /path/to/config:/config
      - /path/to/movies:/movies
      - /path/to/downloads:/torrents
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    image: linuxserver/radarr:latest

  sonarr:
    container_name: sonarr
    restart: unless-stopped
    network_mode: service:transmission-openvpn
    depends_on:
      - transmission-openvpn
    volumes:
      - /path/to/config:/config
      - /path/to/shows:/shows
      - /path/to/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    image: linuxserver/sonarr:latest
    
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: service:transmission-openvpn
    depends_on:
      - transmission-openvpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /path/to/config/:/config
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    network_mode: service:transmission-openvpn
    depends_on:
      - transmission-openvpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /path/to/config:/config
      - /path/to/movies:/movies
      - /path/to/shows:/shows
    restart: unless-stopped
    
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Los_Angeles
      - PORT=5055
    ports:
      - 5055:5055
    volumes:
      - /path/to/config/.app:/app/config
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:nightly
    container_name: readarr
    network_mode: service:transmission-openvpn
    depends_on:
      - transmission-openvpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /path/to/config:/config
      - /path/to/books:/books
      - /path/to/downloads:/downloads
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    network_mode: service:transmission-openvpn
    depends_on:
      - transmission-openvpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /path/to/config:/config
      - /path/to/music:/music
      - /path/to/downloads:/downloads
    restart: unless-stopped
    
  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    volumes:
      - /path/to/downloads/completed:/downloads
    restart: always
    environment:
      - TZ=Americas/Los_Angeles
      - UN_DEBUG=false
      - UN_LOG_FILE=
      - UN_LOG_FILES=10
      - UN_LOG_FILE_MB=10
      - UN_INTERVAL=2m
      - UN_START_DELAY=1m
      - UN_RETRY_DELAY=5m
      - UN_MAX_RETRIES=3
      - UN_PARALLEL=1
      - UN_FILE_MODE=0644
      - UN_DIR_MODE=0755
      - UN_SONARR_0_URL= #Place Sonarr URL Here
      - UN_SONARR_0_API_KEY=28 # Place Sonarr API Key Here
      - UN_SONARR_0_PATHS_0=/downloads
      - UN_SONARR_0_PROTOCOLS=torrent
      - UN_SONARR_0_TIMEOUT=10s
      - UN_SONARR_0_DELETE_ORIG=true
      - UN_SONARR_0_DELETE_DELAY=5m
      - UN_RADARR_0_URL= #Place Radarr URL Here
      - UN_RADARR_0_API_KEY= #Place Radarr API Key Here
      - UN_RADARR_0_PATHS_0=/downloads
      - UN_RADARR_0_PROTOCOLS=torrent
      - UN_RADARR_0_TIMEOUT=10s
      - UN_RADARR_0_DELETE_ORIG=true
      - UN_RADARR_0_DELETE_DELAY=5m
    security_opt:
      - no-new-privileges:true

  transmission-openvpn:
    cap_add:
      - NET_ADMIN
    volumes:
      - /path/to/downloads/:/data
    environment:
      - OPENVPN_PROVIDER= #Place OpenVPN Provider Here (PIA, IPSW, etc)
      - OPENVPN_CONFIG=ca_vancouver
      - OPENVPN_USERNAME=  #Place OpenVPN Username Here
      - OPENVPN_PASSWORD= #Place OpenVPN Password Here
      - LOCAL_NETWORK= #Allowed Networks Here (ex.10.0.10.0/24)
      - TRANSMISSION_WEB_UI=transmissionic
      - TRANSMISSION_PEER_PORT=62348
      - TRANSMISSION_PORT_FORWARD=true
      - PUID=1000
      - PGID=1000
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 9091:9091
      - 7878:7878
      - 8686:8686
      - 8787:8787
      - 6767:6767
      - 9696:9696
      - 8989:8989
    image: haugene/transmission-openvpn:dev
    restart: always
    #   user: 1000:1000
    container_name: transmission
networks: {}
