version: '3'
services:
  radarr:
    container_name: radarr
    restart: unless-stopped
    ports:
      - '7878:7878'
    volumes:
      - '/home/adorsi/radarr/config:/config'
      - '/mnt/media/Movies:/mnt/media/Movies'
      - '/mnt/media/torrents:/mnt/media/torrents'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    image: linuxserver/radarr
  sonarr:
    container_name: sonarr
    restart: unless-stopped
    ports:
      - '8989:8989'
    volumes:
      - '/home/adorsi/sonarr/config:/config'
      - '/mnt/media/Shows:/mnt/media/Shows'
      - '/mnt/media/torrents:/mnt/media/torrents'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    image: linuxserver/sonarr
  prowlarr:
    image: 'lscr.io/linuxserver/prowlarr:latest'
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - '/home/adorsi/prowlarr/:/config'
    ports:
      - '9696:9696'
    restart: unless-stopped
  bazarr:
    image: 'lscr.io/linuxserver/bazarr:latest'
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - '/home/adorsi/bazarr/:/config'
      - '/mnt/media/Movies:/movies'
      - '/mnt/media/Shows:/tv'
    ports:
      - '6767:6767'
    restart: unless-stopped
  transmission-openvpn:
    cap_add:
      - NET_ADMIN
    volumes:
      - '/mnt/media/torrents/:/data'
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=ca_vancouver
      - OPENVPN_USERNAME=p1651372
      - OPENVPN_PASSWORD=QT8pNA7PmG!QKg24q&
      - LOCAL_NETWORK=10.0.10.0/24
      - TRANSMISSION_WEB_UI=flood-for-transmission
      - TRANSMISSION_PEER_PORT=62348
      - TRANSMISSION_PORT_FORWARD=true
      - PUID=1000
      - PGID=1003
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - '9091:9091'
    image: 'haugene/transmission-openvpn:dev'
    restart: always
    user: '0:1000'
    container_name: transmission
  overseerr:
    image: 'sctx/overseerr:latest'
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Los_Angeles
      - PORT=5055
    ports:
      - '5055:5055'
    volumes:
      - '/home/adorsi/overseer/.app:/app/config'
    restart: unless-stopped
