version: '3.3'
services:
    dizquetv:
        image: jasongdove/dizquetv:develop-nvidia
        container_name: dizquetv
        restart: unless-stopped
        ports:
            - 8002:8000
        volumes:
            - /home/plex/dizquetv:/home/node/app/.dizquetv
        environment:
            NVIDIA_VISIBLE_DEVICES: all
            NVIDIA_DRIVER_CAPABILITIES: compute,utility,video
        deploy:
            resources:
                reservations:
                    devices:
                        -   capabilities: [ gpu ]